  var LG = LG || {};

  LG.menuSinCodigos = [
      { id:01, rubro:'sin tacc', nombre:'Muzzarella individual sin T.A.C.C.', descripcion:'' },

      { id:01, rubro:'aperitivos', nombre:'Fernet', descripcion:'' },
      { id:02, rubro:'aperitivos', nombre:'Baileys', descripcion:'' },
      { id:03, rubro:'aperitivos', nombre:'Campari con jugo de naranja', descripcion:'' },
      { id:04, rubro:'aperitivos', nombre:'Cognac', descripcion:'' },
      { id:05, rubro:'aperitivos', nombre:'Gancia Batido con Limón', descripcion:'' },
      { id:06, rubro:'aperitivos', nombre:'Gintonic (incluye Gaseosa)', descripcion:'' },
      { id:07, rubro:'aperitivos', nombre:'Granadina con Soda o 7up', descripcion:'' },
      { id:08, rubro:'aperitivos', nombre:'Tía María', descripcion:'' },
      { id:09, rubro:'aperitivos', nombre:'Whisky Nacional (Criadores)', descripcion:'' },
      { id:10, rubro:'aperitivos', nombre:'Whisky Importado JB', descripcion:'' },
      { id:11, rubro:'aperitivos', nombre:'Whisky Importado Ballantines', descripcion:'' },
      { id:12, rubro:'aperitivos', nombre:'Whisky Etiqueta Roja (J. Walker)', descripcion:'' },
      { id:13, rubro:'aperitivos', nombre:'Whisky Etiqueta Negra (J. Walker)', descripcion:'' },

      { id:01, rubro:'cervezas', nombre:'Isenbeck MANZEN (Roja) (500 ml.)', descripcion:'' },
      { id:02, rubro:'cervezas', nombre:'Isenbeck MANZEN (Roja) (300 ml.)', descripcion:'' },
      { id:03, rubro:'cervezas', nombre:'Isenbeck Pinta (500 ml.)', descripcion:'' },
      { id:04, rubro:'cervezas', nombre:'Isenbeck Media Pinta (300 ml.)', descripcion:'' },
      { id:05, rubro:'cervezas', nombre:'Warsteiner Pinta (500 ml.)', descripcion:'' },
      { id:06, rubro:'cervezas', nombre:'Warsteiner Media Pinta (300 ml.)', descripcion:'' },
      { id:07, rubro:'cervezas', nombre:'Isenbeck Porrón', descripcion:'' },
      { id:08, rubro:'cervezas', nombre:'Miller litro', descripcion:'' },
      { id:09, rubro:'cervezas', nombre:'Miller lite litro', descripcion:'' },
      { id:10, rubro:'cervezas', nombre:'Miller Porrón', descripcion:'' },
      { id:11, rubro:'cervezas', nombre:'Miller Lite Porrón', descripcion:'' },
      { id:12, rubro:'cervezas', nombre:'Warsteiner Porrón', descripcion:'' },
      { id:13, rubro:'cervezas', nombre:'Grolsch Porrón', descripcion:'' },

      { id:01, rubro:'bebidas', nombre:'Agua mineral "bon aqua"', descripcion:'' },
      { id:02, rubro:'bebidas', nombre:'Agua Saborizada (AQUARIUS)', descripcion:'' },
      { id:03, rubro:'bebidas', nombre:'Gaseosas de 1.5 litros (COCA-COLA)', descripcion:'' },
      { id:04, rubro:'bebidas', nombre:'Gaseosas de 330 ml. (COCA-COLA)', descripcion:'' },
      { id:05, rubro:'bebidas', nombre:'Jugo de Naranja Natural', descripcion:'' },
      { id:06, rubro:'bebidas', nombre:'Licuado con Agua', descripcion:'' },
      { id:07, rubro:'bebidas', nombre:'Licuado con Jugo o Leche', descripcion:'' },
      { id:08, rubro:'bebidas', nombre:'Limonada', descripcion:'' },
      { id:09, rubro:'bebidas', nombre:'Soda (Sifón 500 ml.)', descripcion:'' },

      { id:01, rubro:'empanadas', nombre:'Caprese', descripcion:'' },
      { id:02, rubro:'empanadas', nombre:'Carne Cortada a Cuchillo', descripcion:'' },
      { id:03, rubro:'empanadas', nombre:'Carne Dulce', descripcion:'' },
      { id:04, rubro:'empanadas', nombre:'Carne Picante', descripcion:'' },
      { id:05, rubro:'empanadas', nombre:'Carne Suave', descripcion:'' },
      { id:06, rubro:'empanadas', nombre:'Humita', descripcion:'' },
      { id:07, rubro:'empanadas', nombre:'Jamón y Muzzarella', descripcion:'' },
      { id:08, rubro:'empanadas', nombre:'Pollo', descripcion:'' },
      { id:09, rubro:'empanadas', nombre:'Queso y Cebolla', descripcion:'' },
      { id:10, rubro:'empanadas', nombre:'Roquefort', descripcion:'' },
      { id:11, rubro:'empanadas', nombre:'Roquefort y Jamón', descripcion:'' },
      { id:12, rubro:'empanadas', nombre:'Verdura', descripcion:'' },

      { id:01, rubro:'ensaladas', nombre:'Atún', descripcion:'Lechuga, Tomate, Atún, Cebolla y Huevo Duro' },
      { id:02, rubro:'ensaladas', nombre:'Caprese', descripcion:'Tomate, Albahaca, Muzzarella y Aceitunas Negras' },
      { id:03, rubro:'ensaladas', nombre:'Especial', descripcion:'Lechuga, Zanahoria, Jamón Cocido, Palmitos, Tomate y Huevo Duro' },
      { id:04, rubro:'ensaladas', nombre:'La Guitarrita', descripcion:'Rúcula, Espinaca, Jamón Crudo, Provolone Rallado, Tomates Secos y Aceitunas Negras' },
      { id:05, rubro:'ensaladas', nombre:'Primavera', descripcion:'Rúcula, Zanahoria, Tomate, Choclo, Champignones y Huevo Duro' },
      { id:06, rubro:'ensaladas', nombre:'Verde', descripcion:'Rúcula, Espinaca, Lechuga y Cebolla de Verdeo' },

      { id:01, rubro:'pizzas especiales', nombre:'50 ANIVERSARIO', descripcion:'Salsa de tomate, muzzarella, matambre casero, champignones, morrones asados, tomates secos y rúcula fresca' },
      { id:02, rubro:'pizzas especiales', nombre:'ATOMICA', descripcion:'Salsa de tomates, muzzarella, anchoas, morrones, longaniza y jamón cocido natural.' },
      { id:03, rubro:'pizzas especiales', nombre:'BOMBA', descripcion:'Salsa de tomate, muzzarella, anchoas, longaniz a y morrón.' },
      { id:04, rubro:'pizzas especiales', nombre:'BONDIOLA', descripcion:'Salsa de tomate, muzzarella, morrones y bondiola' },
      { id:05, rubro:'pizzas especiales', nombre:'CUARTOS DE FINAL', descripcion:'4 sabores: Provolone, Napolitana, Jamón y Morrones y Calabresa' },
      { id:06, rubro:'pizzas especiales', nombre:'GENOVESA', descripcion:'Salsa de tomate, muzzarella, rodajas de matambre casero, jamón cocido natural, morrones picados, ajíes en vinagre picados y huevo picado' },
      { id:07, rubro:'pizzas especiales', nombre:'GUITARRITA', descripcion:'Salsa de tomate, muzzarella, matambre casero y huevo picado' },
      { id:08, rubro:'pizzas especiales', nombre:'LAS CAÑITAS', descripcion:'Salsa de tomate, muzzarella, morrones asados, jamón cocido natural, cantimpalo y rúcula fresca' },
      { id:09, rubro:'pizzas especiales', nombre:'SUPER GUITARRITA', descripcion:'Salsa de tomate, muzzarella, rodajas de tomate, jamón cocido natural y huevo picado' },
      { id:10, rubro:'pizzas especiales', nombre:'SUPER LAS CAÑITAS', descripcion:'Salsa de tomate, muzzarella, longaniza, tomates secos, morrones, ajíes en vinagre, bondiola y rúcula fresca.' },
      { id:11, rubro:'pizzas especiales', nombre:'TIROLESA', descripcion:'Salsa de tomate, muzzarella, rodajas de matambre casero, jamón cocido natual, morrones, ajíes en vinagre y huevo picado.' },
      { id:12, rubro:'pizzas especiales', nombre:'VENECIANA', descripcion:'Rodajas de cebolla, rodajas de tomate, jamon cocido natural, muzzarella y huevo picado' },

      { id:01, rubro:'faina', nombre:'CON CEBOLLA', descripcion:'' },
      { id:02, rubro:'faina', nombre:'CON JAMON Y MUZZARELLA', descripcion:'' },
      { id:03, rubro:'faina', nombre:'CON MUZZARELLA', descripcion:'' },
      { id:04, rubro:'faina', nombre:'CON MUZZARELLA, TOMATE Y AJO', descripcion:'' },
      { id:05, rubro:'faina', nombre:'CON RUCULA, TOMATE, MUZZARELLA Y AJO', descripcion:'' },
      { id:06, rubro:'faina', nombre:'TRADICIONAL', descripcion:'' },

      { id:01, rubro:'grillitos', nombre:'GRILLITO DE FUGAZZETA CON JAMON', descripcion:'' },
      { id:02, rubro:'grillitos', nombre:'GRILLITO DE JAMON Y QUESO', descripcion:'(Sandwich de empanada relleno con jamon y queso, con provolone gratinado)' },
      { id:03, rubro:'grillitos', nombre:'GRILLITO NAPOLITANO', descripcion:'' },

      { id:01, rubro:'menu-infantil', nombre:'"MENU EMPANADAS"', descripcion:'2 Empanadas, 1 Gaseosa, 1 Bocha de Helado' },
      { id:02, rubro:'menu-infantil', nombre:'"MENU PIZZA"', descripcion:'1 Muzzarella Individual, 1 Gaseosa, 1 Bocha de Helado' },
      { id:03, rubro:'menu-mediodia', nombre:'EMPANADAS', descripcion:'3 Empanadas a elección + 1 Gaseosa ó Quilmes Choop 300 ml. + 1 Café' },
      { id:04, rubro:'menu-mediodia', nombre:'MENÚ "PONTONI"', descripcion:'Pizza individual (Muzzarella / Fugazzetta / Napolitana / Calabresa Anchoas / Cebolla / Jamón / Huevo) + 1 gaseosa ó Quilmes Chopp 300 ml. + Café' },
      { id:05, rubro:'menu-mediodia', nombre:'MENÚ "SAETA RUBIA"', descripcion:'Pizza individual (Muzzarella / Fugazzetta / Napolitana / Calabresa Anchoas / Cebolla / Jamón / Huevo) + 1 gaseosa ó Quilmes Chopp 300 ml. + 1 postre ó café' },
      { id:06, rubro:'menu-mediodia', nombre:'MENU "ATÓMICO"', descripcion:'1 empanada ó fainá + Pizza individual (Jamón y morrones / Fugazzetta con jamón / Rúcula / Provolone / Roquefort / Super Guitarrita / Cantimpalo) + 1 gaseosa ó Quilmes Chopp 300 ml. + 1 postre o café' },
      { id:07, rubro:'menu-mediodia', nombre:'MENU "CHANGO" (2 personas)', descripcion:'2 faina ó empanadas + 1 Pizza Grande napolitana / napolitana / fugazzetta / calabresa / Anchoas / Cebolla / Jamón / Huevo + 2 gaseosas ó Quilmes Chopp 300 ml. + 2 postres ó café' },
      { id:08, rubro:'menu-mediodia', nombre:'MENU "LOS GALACTICOS" ( 4 personas)', descripcion:'4 faina ó empanadas + 2 Pizzas Grandes muzzarella / napolitana / fugazzetta / calabresa / Anchoas / Cebolla / Jamón / Huevo + 4 gaseosas ó Quilmes Chopp + 4 café' },
      { id:09, rubro:'menu-mediodia', nombre:'MENU "MAMUCHO" (2 personas)', descripcion:'2 faina ó empanadas + 1 Pizza Grande Muzzarella / Napolitana / Fugazzetta / Calabresa / Anchoas / Cebolla / Jamón / Huevo + 2 gaseosas ó Quilmes Chopp 300 ml. + 2 café' },

      { id:01, rubro:'picadas', nombre:'Picada Para 2', descripcion:'Incluye 1 chopp de 300 ml. por persona. Jamón crudo, jamón cocido, bondiola, longaniza, cantimpalo, muzzarella, provolone, roquefort, aceitunas, matambre casero, morrones asados con ajo, berenjenas. Se sirve con pan de pizza y timbal de maní' },
      { id:02, rubro:'picadas', nombre:'Picada Para 4', descripcion:'Incluye 1 chopp de 300 ml. por persona. Jamón crudo, jamón cocido, bondiola, longaniza, cantimpalo, muzzarella, provolone, roquefort, aceitunas, matambre casero, morrones asados con ajo, berenjenas. Se sirve con pan de pizza y timbal de maní' },

      { id:01, rubro:'pizzas', nombre:'ALBAHACA', descripcion:'Salsa de tomate, muzzarella y albahaca.' },
      { id:02, rubro:'pizzas', nombre:'ALBAHACA', descripcion:'Salsa de tomate, muzzarella y albahaca' },
      { id:03, rubro:'pizzas', nombre:'ANANA con JAMON', descripcion:'Salsa de tomate, muzzarella, rodajas de ananá y jamón cocido natural.' },
      { id:04, rubro:'pizzas', nombre:'ANANA', descripcion:'Salsa de tomate, muzzarella y rodajas de ananá.' },
      { id:05, rubro:'pizzas', nombre:'ANANA', descripcion:'Salsa de tomate, muzzarella y rodajas de ananá' },
      { id:06, rubro:'pizzas', nombre:'ANCHOAS', descripcion:'Salsa de tomate y filetes de anchoas.' },
      { id:07, rubro:'pizzas', nombre:'Atún', descripcion:'Muzzarella, lomito de atún al natural, rodajas de tomate y cebolla' },
      { id:08, rubro:'pizzas', nombre:'ATOMICA', descripcion:'Salsa de tomate, muzzarella, anchoas, morrones, longaniza y jamón cocido natural' },
      { id:09, rubro:'pizzas', nombre:'ATUN', descripcion:'Rodajas de cebolla y lomitos de atún.' },
      { id:10, rubro:'pizzas', nombre:'BERENJENAS', descripcion:'Salsa de tomate, espinaca, berenjenas asadas, muzzarella y morrones (ajo a gusto).' },
      { id:11, rubro:'pizzas', nombre:'BOMBA', descripcion:'Salsa de tomate, muzzarella, anchoas, longaniza y morrón' },
      { id:12, rubro:'pizzas', nombre:'Bondiola', descripcion:'Salsa de tomate, muzzarella, morrones y bondiola' },
      { id:13, rubro:'pizzas', nombre:'CALABRESA', descripcion:'Salsa de tomate, muzzarella y longaniza.' },
      { id:14, rubro:'pizzas', nombre:'CANTIMPALO', descripcion:'Salsa de tomate, muzzarella, morrones y cantimpalo.' },
      { id:15, rubro:'pizzas', nombre:'Caprese', descripcion:'Muzzarella, tomate, albahaca y aceitunas negras' },
      { id:16, rubro:'pizzas', nombre:'CEBOLLA', descripcion:'Rodajas de cebolla.' },
      { id:17, rubro:'pizzas', nombre:'CHAMPIGNONES', descripcion:'Jamón cocido natural, muzzarella, cebolla de verdeo y champignones frescos.' },
      { id:18, rubro:'pizzas', nombre:'DOBLE MUZZARELLA', descripcion:'Salsa de tomate y doble porción de muzzarella.' },
      { id:19, rubro:'pizzas', nombre:'DON GRILLO', descripcion:'Pizza rellena con muzzarella, jamón cocido natural, longaniza, y morrón, cubierta con provolone' },
      { id:20, rubro:'pizzas', nombre:'ESPARRAGOS', descripcion:'Salsa de tomate, salsa blanca, muzzarella, esparragos, cebolla de verdeo y provolone rallado.' },
      { id:21, rubro:'pizzas', nombre:'FIORENTINA', descripcion:'Salsa de tomate, muzzarella, rodajas de tomate, longaniza y huevo picado.' },
      { id:22, rubro:'pizzas', nombre:'FUGAZZETTA con JAMON', descripcion:'Muzzarella, rodajas de cebolla y jamón cocido natural.' },
      { id:23, rubro:'pizzas', nombre:'FUGAZZETTA con JAMON y PROVOLONE', descripcion:'Rodajas de cebolla, muzzarella, jamón cocido natural y provolone.' },
      { id:24, rubro:'pizzas', nombre:'FUGAZZETTA con PROVOLONE', descripcion:'Rodajas de cebolla, muzzarella y provolone.' },
      { id:25, rubro:'pizzas', nombre:'FUGAZZETTA', descripcion:'Muzzarella y rodajas de cebolla.' },
      { id:26, rubro:'pizzas', nombre:'HUEVO', descripcion:'Salsa de tomate, muzzarella y huevo picado.' },
      { id:27, rubro:'pizzas', nombre:'HUMITA', descripcion:'Salsa de tomate, muzzarella y choclo desgranado.' },
      { id:28, rubro:'pizzas', nombre:'JAMÓN y HUEVO', descripcion:'Salsa de tomate, muzzarella, jamón cocido natural y huevo picado.' },
      { id:29, rubro:'pizzas', nombre:'JAMON', descripcion:'Salsa de tomate, muzzarella y jamón cocido natural.' },
      { id:30, rubro:'pizzas', nombre:'JAMON y MORRONES', descripcion:'Salsa de tomate, muzzarella, morrones y jamón cocido natural.' },
      { id:31, rubro:'pizzas', nombre:'LA MAQUINA', descripcion:'Salsa de tomate, jamón cocido natural, muzzarella, morrones asados, huevo picado y aceitunas negras trozadas.' },
      { id:32, rubro:'pizzas', nombre:'MORRONES', descripcion:'Salsa de tomate, muzzarella y morrones asados.' },
      { id:33, rubro:'pizzas', nombre:'MUZZARELLA con ANCHOAS', descripcion:'Salsa de tomate, muzzarella y filetes de anchoas.' },
      { id:34, rubro:'pizzas', nombre:'MUZZARELLA', descripcion:'Salsa de tomate y muzzarella.' },
      { id:35, rubro:'pizzas', nombre:'NAPOLITANA con JAMON', descripcion:'Salsa de tomate, muzzarella, rodajas de tomate, jamón cocido natural y albahaca. (ajo a gusto).' },
      { id:36, rubro:'pizzas', nombre:'NAPOLITANA', descripcion:'Salsa de tomate, muzzarella, rodajas de tomate y albahaca (ajo a gusto).' },
      { id:37, rubro:'pizzas', nombre:'NAVIDEÑA', descripcion:'Salsa de tomate, muzzarella, morrones asados, rodajas de ananá, champignones, tomates secos y rúcula.' },
      { id:38, rubro:'pizzas', nombre:'PALMITOS con JAMÓN', descripcion:'Salsa de tomate, muzzarella, palmitos, jamón cocido natural y huevo picado.' },
      { id:39, rubro:'pizzas', nombre:'PALMITOS', descripcion:'Salsa de tomate, muzzarella, palmitos y huevo picado.' },
      { id:40, rubro:'pizzas', nombre:'PANCETA A CABALLO', descripcion:'Muzzarella, rodajas de cebolla, panceta y huevos.' },
      { id:41, rubro:'pizzas', nombre:'PANCETA', descripcion:'Muzzarella, rodajas de cebolla y panceta.' },
      { id:42, rubro:'pizzas', nombre:'PAPA-CHICHA', descripcion:'Salsa de tomate, muzzarella, rodajas de salchicha y papas pay.' },
      { id:43, rubro:'pizzas', nombre:'PIZZAIOLA', descripcion:'Salsa de tomate y ajo picado.' },
      { id:44, rubro:'pizzas', nombre:'PROVOLONE con JAMÓN', descripcion:'Salsa de tomate, muzzarella y provolone. Y jamon cocido natural' },
      { id:45, rubro:'pizzas', nombre:'PROVOLONE', descripcion:'Salsa de tomate, muzzarella y provolone.' },
      { id:46, rubro:'pizzas', nombre:'ROMANA', descripcion:'Salsa de tomate, muzzarella, rodajas de tomate y huevo picado.' },
      { id:47, rubro:'pizzas', nombre:'ROQUEFORT con CEBOLLA', descripcion:'Rodajas de cebolla, muzzarella y queso azul.' },
      { id:48, rubro:'pizzas', nombre:'ROQUEFORT', descripcion:'Salsa de tomate, muzzarella y queso azul.' },
      { id:49, rubro:'pizzas', nombre:'RUCULA con JAMON CRUDO', descripcion:'Salsa de tomate, muzzarella, tomates secos, jamón crudo y rúcula fresca.' },
      { id:50, rubro:'pizzas', nombre:'RUCULA', descripcion:'Salsa de tomate, muzzarella, tomates seco y rúcula fresca.' },
      { id:51, rubro:'pizzas', nombre:'SICILIANA', descripcion:'Salsa de tomate, muzzarella, ajíes en vinagre y jamón cocido natural.' },
      { id:52, rubro:'pizzas', nombre:'TRES QUESOS', descripcion:'Salsa de tomate, muzzarella, provolone y queso azul.' },
      { id:53, rubro:'pizzas', nombre:'VERDURA con SALSA BLANCA', descripcion:'Espinaca, salsa blanca, muzzarella y provolone.' },
      { id:54, rubro:'pizzas', nombre:'VERDURA', descripcion:'Salsa de tomate, muzzarella, espinaca salteada con ajo y provolone y huevo picado.' },

      { id:01, rubro:'pizzas rellenas', nombre:'DON GRILLO', descripcion:'Pizza rellena con muzzarella, jamón cocido natural, longaniza, y morrón, cubierta con provolone.' },
      { id:02, rubro:'pizzas rellenas', nombre:'FARINETA', descripcion:'Pizza rellena con muzzarella, cebolla, jamón cocido natural y rodajas de tomate.' },
      { id:03, rubro:'pizzas rellenas', nombre:'FUGAZZETTA con JAMON y PROVOLONE', descripcion:'Pizza rellena con muzzarella, jamón cocido natural y rodajas de cebolla, cubierta con cebolla y provolone.' },
      { id:04, rubro:'pizzas rellenas', nombre:'FUGAZZETTA', descripcion:'Pizza rellena con muzzarella, rodajas de cebolla, cubierta con cebolla.' },
      { id:05, rubro:'pizzas rellenas', nombre:'MADRILEÑA', descripcion:'Pizza rellena con muzzarella, salsa de tomate, rodajas de tomate, jamón y huevo picado.' },

      { id:01, rubro:'postres', nombre:'Almendrado', descripcion:'' },
      { id:02, rubro:'postres', nombre:'Banana con Dulce de Leche y/o Crema', descripcion:'' },
      { id:03, rubro:'postres', nombre:'Banana Split', descripcion:'3 Bochas de Helado a elección, Banana, Chocolate Caliente, Dulce de Leche y Crema Chantilly' },
      { id:04, rubro:'postres', nombre:'Bombón Escocés', descripcion:'' },
      { id:05, rubro:'postres', nombre:'Casata', descripcion:'' },
      { id:06, rubro:'postres', nombre:'Charlotte', descripcion:'' },
      { id:07, rubro:'postres', nombre:'Chocotorta', descripcion:'' },
      { id:08, rubro:'postres', nombre:'Chulito', descripcion:'Helado de Crema sobre Merengue y dulce de Leche, cubierto con Almendras Caramelizadas y Chocolate caliente' },
      { id:09, rubro:'postres', nombre:'Don Pedro', descripcion:'Helado almendrado, crema Chantilly y Whisky' },
      { id:00, rubro:'postres', nombre:'Duraznos en Almíbar', descripcion:'' },
      { id:11, rubro:'postres', nombre:'Ensalada de Frutas con Helado', descripcion:'' },
      { id:12, rubro:'postres', nombre:'Ensalada de Frutas', descripcion:'' },
      { id:13, rubro:'postres', nombre:'Flan Casero', descripcion:'' },
      { id:14, rubro:'postres', nombre:'Flan Mixto', descripcion:'' },
      { id:15, rubro:'postres', nombre:'Frutillas con Crema o Jugo de Naranja', descripcion:'' },
      { id:16, rubro:'postres', nombre:'Helados El Fundador', descripcion:'1, 2 o 3 Bochas. Dulce de Leche, Crema Americana, Chocolate, Frutilla, Vainilla y Limón' },
      { id:17, rubro:'postres', nombre:'La Guitarrita', descripcion:'Helado Casata, Crema Chantilly, Duraznos en Almibar, Obleas y Chocolate Caliente.' },
      { id:18, rubro:'postres', nombre:'Marcianito', descripcion:'Helado Casata, Crema Chantilly, Dulce de Leche, Obleas y Chocolate Caliente' },
      { id:19, rubro:'postres', nombre:'Merengue', descripcion:'Mixto: Crema y Duraznos/Crema y Frutillas' },
      { id:20, rubro:'postres', nombre:'Mousse de Chocolate', descripcion:'' },
      { id:21, rubro:'postres', nombre:'Panqueque con Dulce de Leche', descripcion:'' },
      { id:22, rubro:'postres', nombre:'Panqueque con Dulce de Leche y Helado', descripcion:'' },
      { id:23, rubro:'postres', nombre:'Queso y Dulce (membrillo o batata)', descripcion:'' },
      { id:24, rubro:'postres', nombre:'Tarantella', descripcion:'' },
      { id:25, rubro:'postres', nombre:'Tiramisú', descripcion:'' }
    ];
